emailVerification/urls.py
from django.contrib import admin
from django.urls import path, include
from verifier import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verify/',include('verifier.urls',namespace='verify')),
    path('',views.Index,name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

verifier/urls.py
from django.urls import path, re_path
from . import views

app_name = 'verify'

urlpatterns = [
    path('list/',views.ListUpload,name='list'),
    path('single/',views.SingleEmail,name='single'),
    re_path(r'^download/(?P<pk>\d+)/$',views.Download,name='download')
]

verifier/models.py
from django.db import models
from django.core.validators import EmailValidator,FileExtensionValidator

# Create your models here.


class Documents(models.Model):
    email = models.CharField(max_length = 60,validators=[EmailValidator])
    doc_name = models.FileField(upload_to='documents/',validators=[FileExtensionValidator(allowed_extensions=['csv'])])
    verified = models.BooleanField(default=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
    def __Str__(self):
        return self.doc_name

class IPUsers(models.Model):
    ip_address = models.CharField(max_length=120, default='ABC')
    visted = models.BooleanField(default=False)
    timestamp = models.DateTimeField(blank=True, null=True,auto_now_add=True)

    def __str__(self):
        return self.ip_address

verifier/forms.py
from .models import Documents
from django import forms
from django.core.validators import FileExtensionValidator



class SingleForm(forms.ModelForm):
    email = forms.CharField(widget=forms.EmailInput())
    
    class Meta:
        model = Documents
        fields = ['email',]


class ListForm(forms.ModelForm):
    email = forms.CharField(widget=forms.EmailInput(),help_text='You will recieve a download link on this email')
    doc_name = forms.FileField(validators=[FileExtensionValidator(allowed_extensions=['csv'],message='only csv files are allowed')])
    class Meta:
        model = Documents
        fields = ['email','doc_name']

verifier/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from django.contrib import messages
import csv
from django.utils import timezone
from django.conf import settings
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template


from . import forms
from . import models
from .tasks import verify_list
from .VerifyEmailAddress import verify_email
# Create your views here.


def get_ip(request):
    try:
        x_forward = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forward:
            ip = x_forward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ""
    return ip

def Index(request):
    return render(request,'Index.html',{'form':forms.ListForm()})

def SingleEmail(request):
    data = []
    cur_email = "none"
    
    if request.method == 'POST':
        form = forms.SingleForm(request.POST)
        if form.is_valid():
            email = form.save(commit=False)
            cur_email = email.email
            datadict = verify_email(email.email)

            data.append(datadict['user'])
            data.append(datadict['domain'])
            data.append(datadict['code'])
            
            if datadict['code'] == 250:
                data.append('deliverable')
                data.append(datadict['message'])
                data.append('True')
            elif datadict['code'] == 550:
                data.append('undeliverable')
                data.append(datadict['message'])
                data.append('True')
            else:
                data.append('Unknown')
                data.append(datadict['message'])
                data.append('False')

        form = forms.SingleForm()
        return render(request,'verifier/Single_email.html',{'form':form,'data':data,'email':cur_email})
    else:
        form = forms.SingleForm()

    return render(request,'verifier/Single_email.html',{'form':form,'data':data,'email':cur_email})

def ListUpload(request):
    my_ip = get_ip(request)
    ip = models.IPUsers.objects.get(ip_address=my_ip)
    
    if request.method == "POST":
        form = forms.ListForm(request.POST,request.FILES)
        if form.is_valid():
            email_list = form.save(commit=True)
            with open(f'media/{email_list.doc_name}','r') as csv_file:
                csv_reader = csv.reader(csv_file,delimiter=',')
                count = 0
                for column in csv_reader:
                    if count == 0:
                        for col_names in column:
                            if col_names == 'email':
                                count = count + 1
                        if count == 1:
                            url = str(email_list.doc_name)
                            verify_list.delay(url)
                            ip,created = models.IPUsers.objects.get_or_create(ip_address=my_ip)
                            ip.visted = True
                            ip.timestamp = timezone.now()
                            ip.save()
                            messages.success(request,"The File has been submitted Successfully. You will recieve an email when your file has been verified")
                        else:
                            messages.error(request,"This csv file doesn't contain the emails column or there are 2 columns named 'email' ")
                        count = count + 1
                    else:
                        break
        else:
            messages.error(request,'No csv file detected')            
            
        return redirect('verify:list')

    else:
        form = forms.ListForm

    return render(request,'verifier/List_upload.html',{'ip':ip,'form':form})

def Download(request,pk):
    File = get_object_or_404(models.Documents, pk=pk)

    response = HttpResponse(content_type='text/csv')
    response['content-Disposition'] = 'attachment; filename="Verified_Emails_list.csv"'

    with open(f'media/{File.doc_name}','r') as csv_file:
        csv_reader = csv.reader(csv_file,delimiter=',')

        writer = csv.writer(response, delimiter=',')

        for obj in csv_reader:
            writer.writerow(obj)

    return response

templates/Index.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}



{% block content %}

<div class="container mt-3">
<div class="dropdown-divider border-success"></div>
<div class="row my-3">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item text-truncate btn-outline-info list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home" title="Single Verification">Single Verification</a>
      <a class="list-group-item text-truncate btn-outline-info list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile" title="List Verification">List Verification</a>
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
            <h3>Steps To verify an email address</h3>
            <ul>
                <li>
                    To verify an email adress first go to the link named Single Email Verification or <a href="{% url 'verify:single' %}">click here.</a>
                </li>
                <li>
                    Enter the email address you want to verify in the field and press submit.
                </li>
                <li>
                    The results will be displayed just bellow the submit button.
                </li>
            </ul>
        </div>
        <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
            <h3>Steps To verify more than one email addresses</h3>
            <ul>
                <li>
                    To verify more than one email adress in one go. First go to the link named List Upload or <a href="{% url 'verify:list' %}">click here.</a>
                </li>
                <li>
                    Enter your email address so that we contact you when the your emails have verified.
                </li>
                <li>
                    Upload a csv file containing the list of your email address you want to verify.<br/>
                    your list will look something like this:
                    <img style="float-right" src="{% static 'icon/list.png' %}">
                </li>
                <li>
                    Press the Submit button.
                </li>
                <li>
                    An email address will be sent to you for a csv file which contains the list of verified email.
                    <br/>
                    Note: This list will be deleted withing 24 hours from the time when you recieve your email.
                </li>
            </ul>
        </div>
    </div>
  </div>

</div>
<div class="dropdown-divider border-success"></div>
</div>

{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}


<html lang="en">

	<!-- begin::Head -->
	<head>
		<meta charset="utf-8" />
		<title>
		{% block title %}
			Dashboard
		{% endblock title %}
		</title>
		<meta name="description" content="Latest updates and statistic charts">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

		<!--begin::Web font -->
		<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
		<script>
			WebFont.load({
            google: {"families":["Montserrat:300,400,500,600,700","Roboto:300,400,500,600,700"]},
            active: function() {
                sessionStorage.fonts = true;
            }
          });
        </script>

		<!--end::Web font -->

		<!--begin:: Global Mandatory Vendors -->
		{% comment %} <link href="{% static 'css/vendors/perfect-scrollbar/css/perfect-scrollbar.css' %}" rel="stylesheet" type="text/css" /> {% endcomment %}

		<!--end:: Global Mandatory Vendors -->

		<!--begin:: Global Optional Vendors -->
		<link href="{% static 'css/vendors/vendors/line-awesome/css/line-awesome.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/vendors/vendors/flaticon/css/flaticon.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/vendors/vendors/metronic/css/styles.css' %}" rel="stylesheet" type="text/css" />

		<!--end:: Global Optional Vendors -->

		<!--begin::Global Theme Styles -->
		<link href="{% static 'css/vendors/assets/demo/base/style.bundle.css' %}" rel="stylesheet" type="text/css" />

		<!--RTL version:<link href="assets/demo/base/style.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

		<!--end::Global Theme Styles -->

		<!--begin::Page Vendors Styles -->
		
		<!--RTL version:<link href="assets/vendors/custom/fullcalendar/fullcalendar.bundle.rtl.css" rel="stylesheet" type="text/css" />-->

		<!--end::Page Vendors Styles -->
	</head>

	<!-- end::Head -->

	<!-- begin::Body -->
	<body style="background-image: url({% static 'css/vendors/assets/app/media/img/bg/bg-1.jpg' %})" class="m-page--boxed m-body--fixed m-header--static m-aside--offcanvas-default">

		<!-- begin:: Page -->
		<div class="m-grid m-grid--hor m-grid--root m-page">

			<!-- begin::Header -->
			<header id="m_header" class="m-grid__item	m-grid m-grid--desktop m-grid--hor-desktop  m-header ">
				<div class="m-grid__item m-grid__item--fluid m-grid m-grid--desktop m-grid--hor-desktop m-container m-container--responsive m-container--xxl">
					<div class="m-grid__item m-grid__item--fluid m-grid m-grid--desktop m-grid--ver-desktop m-header__wrapper">

						<!-- begin::Brand -->
						<div class="m-grid__item m-brand">
							<div class="m-stack m-stack--ver m-stack--general m-stack--inline">
								<div class="m-stack__item m-stack__item--middle m-brand__logo">
									<a href="index.html" class="m-brand__logo-wrapper">
										<img alt="{% url 'home' %}" src="{% static 'css/vendors/assets/demo/media/img/logo/logo.png'%}" />
									</a>
								</div>
                                {% block top_dropdown %}  
								<div class="m-stack__item m-stack__item--middle m-brand__tools">
									<div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-left m-dropdown--align-push" m-dropdown-toggle="click" aria-expanded="true">
										<a href="" class="dropdown-toggle m-dropdown__toggle btn btn-outline-metal m-btn  m-btn--icon m-btn--pill">
											<span>Dashboard</span>
										</a>
										<div class="m-dropdown__wrapper">
											<span class="m-dropdown__arrow m-dropdown__arrow--left m-dropdown__arrow--adjust"></span>
											<div class="m-dropdown__inner">
												<div class="m-dropdown__body">
													<div class="m-dropdown__content">
														<ul class="m-nav">
															<li class="m-nav__section m-nav__section--first m--hide">
																<span class="m-nav__section-text">Quick Menu</span>
															</li>  
                                                            <li class="m-nav__item">
                                                                <a href="{% url 'verify:single' %}" class="m-nav__link">
                                                                    <i class="m-nav__link-icon flaticon-share"></i>
                                                                    <span class="m-nav__link-text">Single Email Verification</span>
                                                                </a>
                                                            </li>
                                                            <li class="m-nav__item">
                                                                <a href="{% url 'verify:list' %}" class="m-nav__link">
                                                                    <i class="m-nav__link-icon flaticon-chat-1"></i>
                                                                    <span class="m-nav__link-text">Bulk Email Verification</span>
                                                                </a>
                                                            </li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
                                    {% endblock top_dropdown %}

									<!-- begin::Responsive Header Menu Toggler-->
									<a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
										<span></span>
									</a>

									<!-- end::Responsive Header Menu Toggler-->

									<!-- begin::Topbar Toggler-->
									<a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
										<i class="flaticon-more"></i>
									</a>

									<!--end::Topbar Toggler-->
								</div>
							</div>
						</div>

						<!-- end::Brand -->

						<!-- begin::Topbar -->
                            <div class="m-grid__item m-grid__item--fluid m-header-head" id="m_header_nav">

							<div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
								<div class="m-stack__item m-topbar__nav-wrapper">
									<ul class="m-topbar__nav m-nav m-nav--inline">
										<li class="m-nav__item m-topbar__notifications m-topbar__notifications--img m-dropdown m-dropdown--large m-dropdown--header-bg-fill m-dropdown--arrow m-dropdown--align-center 	m-dropdown--mobile-full-width" m-dropdown-toggle="click"
										 m-dropdown-persistent="1">
											<a href="{% url 'admin:login' %}" class="m-nav__link" id="m_topbar_notification_icon">
												<span class="m-nav__link-icon">
                                                <span class="m-link btn">
                                                <button type="button" class="btn btn-white">Admin</button>
                                                </span>
                                                </span>
											</a>
										</li>
									</ul>
								</div>
							</div>

						</div>
						<!-- end::Topbar -->
					</div>
				</div>
			</header>

			<!-- end::Header -->

			<!-- begin::Body -->
			<div class="m-grid__item m-grid__item--fluid m-grid m-grid m-grid--hor m-container m-container--responsive m-container--xxl">
				<div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor-desktop m-grid--desktop m-body">
					<div class="m-grid__item m-body__nav">
						<div class="m-stack m-stack--ver m-stack--desktop">

							<!-- begin::Horizontal Menu -->
							{% block navbar %}
                            <div class="m-stack__item m-stack__item--middle m-stack__item--fluid">
								<button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-light " id="m_aside_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
								<div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-light m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-light m-aside-header-menu-mobile--submenu-skin-light ">
									<ul class="m-menu__nav  m-menu__nav--submenu-arrow ">
										<li class="m-menu__item  m-menu__item--active" aria-haspopup="true">
                                            <a href="{% url 'home' %}" class="m-menu__link ">
                                                <span class="m-menu__item-here"></span>
                                                <span class="m-menu__link-text">Dashboard</span>
                                            </a>
                                        </li>
										
                                        <li class="m-menu__item" m-menu-submenu-toggle="click" aria-haspopup="true">
                                            <a href="{% url 'verify:single' %}" class="m-menu__link" title="To verify a single email address">
                                                <span class="m-menu__item-here"></span>
                                                <span class="m-menu__link-text">Single Email Verification</span>
                                            </a>
                                        </li>
                                        
										<li class="m-menu__item" m-menu-submenu-toggle="click" aria-haspopup="true">
                                        <a href="{% url 'verify:list' %}" class="m-menu__link" title="To verify a list of email addresses">
                                                <span class="m-menu__item-here"></span>
                                                <span class="m-menu__link-text">List Upload</span>
                                            </a>
										</li>                                        
									</ul>
								</div>
							</div>
                            {% endblock navbar %}

							<!-- end::Horizontal Menu -->

						</div>
					</div>
					<div class="m-grid__item m-grid__item--fluid m-grid m-grid--desktop m-grid--ver-desktop m-body__content">
						<div class="m-grid__item m-grid__item--fluid m-wrapper">

							<!-- BEGIN: Subheader -->
							<div class="m-subheader ">
								<div class="d-flex align-items-center">
									<div class="mr-auto">
										<h3 class="m-subheader__title ">{% block content_header %}
                                        Dashboard
                                        {% endblock content_header %}</h3>
									</div>
								</div>
							</div>

							<!-- END: Subheader -->
							<div class="m-content">

								<!--Begin::Section-->
								<div class="row">
									<div class="col-xl-12">

										<!--begin::Portlet-->
										<div class="m-portlet  m-portlet--rounded" id="m_portlet">
											<div class="m-portlet__body">
												<div id="m_calendar">
                                                    {% block content %}
                                                    {% comment %} main content goes here {% endcomment %}
                                                    {% endblock content %}
                                                </div>
											</div>
										</div>

										<!--end::Portlet-->
									</div>
								</div>
    							<!--End::Section-->
							
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- begin::Body -->

			<!-- begin::Footer -->
			<footer class="m-grid__item		m-footer ">
				<div class="m-container m-container--responsive m-container--xxl">
					<div class="m-footer__wrapper">
						<div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
							<div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
								<span class="m-footer__copyright">
									2017 &copy; Metronic theme by <a href="https://keenthemes.com" class="m-link">Keenthemes</a>
								</span>
							</div>
							<div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
								<ul class="m-footer__nav m-nav m-nav--skin-dark m-nav--inline m--pull-right">
									<li class="m-nav__item">
										<a href="#" class="m-nav__link">
											<span class="m-nav__link-text">About</span>
										</a>
									</li>
									<li class="m-nav__item">
										<a href="#" class="m-nav__link">
											<span class="m-nav__link-text">Privacy</span>
										</a>
									</li>
									<li class="m-nav__item">
										<a href="#" class="m-nav__link">
											<span class="m-nav__link-text">T&C</span>
										</a>
									</li>
									<li class="m-nav__item">
										<a href="#" class="m-nav__link">
											<span class="m-nav__link-text">Purchase</span>
										</a>
									</li>
									<li class="m-nav__item m-nav__item--last">
										<a href="#" class="m-nav__link" data-toggle="m-tooltip" title="Support Center" data-placement="left">
											<i class="m-nav__link-icon flaticon-info m--icon-font-size-lg3"></i>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</footer>
		</div>


		<!-- end:: Page -->

		
		<!-- begin::Scroll Top -->
		<div id="m_scroll_top" class="m-scroll-top">
			<i class="la la-arrow-up"></i>
		</div>

		<!-- end::Scroll Top -->

		<!--begin:: Global Mandatory Vendors -->
		<script src="{% static 'css/vendors/jquery/dist/jquery.js'%}" type="text/javascript"></script>
		
		<!--end:: Global Mandatory Vendors -->

		<!--begin:: Global Optional Vendors -->

		<!--end:: Global Optional Vendors -->

		<!--begin::Global Theme Bundle -->
		<script src="{% static 'css/vendors/assets/demo/base/scripts.bundle.js'%}" type="text/javascript"></script>

		<!--end::Global Theme Bundle -->

		<!--begin::Page Vendors -->

		<!--end::Page Vendors -->

		<!--begin::Page Scripts -->

		<!--end::Page Scripts -->
	</body>

	<!-- end::Body -->
</html>

templates/include/forms.html
{% load widget_tweaks %}
{% load static %}
{% load staticfiles %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            <p {% if forloop.non_field_errors %}
               class = "mb-0"
               {% endif %}>
                {{error}}
            </p>
        {% endfor %}
    </div>
{% endif %}
        

{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {% if form.is_bound %}
            {{% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    </div class="invalid-feedback">{{error}}</div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}
        {% if field.help_text %}
        <small class="form-text text-muted">
            {{ fieldd.help_text|safe }}
        </small>
        {% endif %}
    </div>
{% endfor %}

templates/verifier/List_upload.html
{% extends "base.html" %}

{% load static %}
{% load staticfiles %}

{% block title %}
  Bulk Upload
{% endblock title %}

{% block top_dropdown %}  
  <div class="m-stack__item m-stack__item--middle m-brand__tools">
    <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-left m-dropdown--align-push" m-dropdown-toggle="click" aria-expanded="true">
      <a href="" class="dropdown-toggle m-dropdown__toggle btn btn-outline-metal m-btn  m-btn--icon m-btn--pill">
        <span>List Upload</span>
      </a>
      <div class="m-dropdown__wrapper">
        <span class="m-dropdown__arrow m-dropdown__arrow--left m-dropdown__arrow--adjust"></span>
        <div class="m-dropdown__inner">
          <div class="m-dropdown__body">
            <div class="m-dropdown__content">
              <ul class="m-nav">
                <li class="m-nav__section m-nav__section--first m--hide">
                  <span class="m-nav__section-text">Quick Menu</span>
                </li>  
                    <li class="m-nav__item">
                        <a href="{% url 'home' %}" class="m-nav__link">
                            <i class="m-nav__link-icon flaticon-share"></i>
                            <span class="m-nav__link-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="{% url 'verify:single' %}" class="m-nav__link">
                            <i class="m-nav__link-icon flaticon-chat-1"></i>
                            <span class="m-nav__link-text">Single Email Verification</span>
                        </a>
                    </li>
              </ul>
          </div>
        </div>
      </div>
    </div>
	</div>
{% endblock top_dropdown %}

{% block navbar %}
<div class="m-stack__item m-stack__item--middle m-stack__item--fluid">
  <button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-light " id="m_aside_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
    <div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-light m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-light m-aside-header-menu-mobile--submenu-skin-light ">
      <ul class="m-menu__nav  m-menu__nav--submenu-arrow ">
        <li class="m-menu__item" aria-haspopup="true">
            <a href="{% url 'home' %}" class="m-menu__link ">
                <span class="m-menu__item-here"></span>
                <span class="m-menu__link-text">Dashboard</span>
            </a>
        </li>

        <li class="m-menu__item" m-menu-submenu-toggle="click" aria-haspopup="true">
            <a href="{% url 'verify:single' %}" class="m-menu__link" title="To verify a single email address">
                <span class="m-menu__item-here"></span>
                <span class="m-menu__link-text">Single Email Verification</span>
            </a>
        </li>
            
        <li class="m-menu__item m-menu__item--active" m-menu-submenu-toggle="click" aria-haspopup="true">
              <a href="{% url 'verify:list' %}" class="m-menu__link" title="To verify a list of email addresses">
                  <span class="m-menu__item-here"></span>
                  <span class="m-menu__link-text">List Upload</span>
              </a>
        </li>                                        
      </ul>
    </div>
</div>
{% endblock navbar %}


{% block content_header %}
List Upload
{% endblock content_header %}

{% block content %}

{% if messages %}

{% for message in messages %}
    <div class="row justify-content-center m-3">
          <div class="card-body">
              <div class="alert alert-info" role="alert">{{ message|safe }}</div>
             <form method="post" enctype="multipart/form-data">
                <img src="{% static 'icon/csv.png' %}" style="width: 100px; height: 130px;" class="rounded mx-auto d-block">
                {% csrf_token %}
                {% include 'include/forms.html' %}
              {% if ip.visted %}
                  <h3>You have already verified a list once please come back in 3 days.</h3>
              {% else %}
                  <button type="submit" class="btn btn-primary btn-block">Submit</button>
              {% endif %}
            </form>
          </div>
    </div>
    {% endfor %}
{% else %}
<div class="row justify-content-center">
          <div class="card-body">
             <form method="post" enctype="multipart/form-data">
                <img src="{% static 'icon/csv.png' %}" style="width: 100px; height: 130px;" class="rounded mx-auto d-block">
                {% csrf_token %}
                {% include 'include/forms.html' %}
              {% if ip.visted %}
                  <h3>You have already verified a list once please come back in 3 days.</h3>
              {% else %}
                  <button type="submit" class="btn btn-primary btn-block">Submit</button>
              {% endif %}
            </form>
      </div>
    </div>
  {% endif %}

{% endblock content %}

templates/verifier/download_list_email.html
<h1>Hi there,</h1>

<h2>The email list you submitted along with you email : {{ email.email }}  is complete.
<br>
To download it click the link bellow,</h2>

{{ protocol }}://{{ domain }}{% url 'verify:download' pk=email.pk %}

<h4>If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.</h4>

<p>If you didn't request this email. Then Please Ignore</p>

<h1>Thanks,</h1> 